### ISSUE TITLE
Add GitHub Action for publishing .apk

### ISSUE THREAD

**Issue by davidkroell** [davidkroell/docker2go#16]
I already have an GitHub action which builds my code and checks for errors.

In addition to this, I would like to have an Action whichs releases the built APK when i create a release, or a tag gets pushed (should check if the correct tag name is set (format: vX.X; for example: v1.2)

Regards,
David

**Comment by aayush287** [comment]
Hi David! I would like to work on this. Can you assign this to me?

**Comment by davidkroell** [comment]
This would be awesome, thank you @aayush287

**Comment by aayush287** [comment]
@davidkroell Opened a PR #17 Please review it
